# Generated by Django 4.2.3 on 2024-09-26 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0017_remove_resourcegroup_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accesspolicy",
            name="resource_group",
        ),
        migrations.AddField(
            model_name="accesspolicy",
            name="resource_groups",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1024),
                default=["1"],
                size=None,
                verbose_name="List of ResourceGroup user_codes",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resourcegroup",
            name="user_code",
            field=models.CharField(
                default=1,
                help_text="Unique code of the ResourceGroup. Used in Configuration and Permissions Logic",
                max_length=1024,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
