# Generated by Django 4.2.3 on 2024-09-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0019_alter_accesspolicy_resource_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourcegroupassignment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="resourcegroupassignment",
            name="modified_at",
        ),
    ]
