services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./poms:/var/app/poms
    restart: always
    depends_on:
      - db
      - rabbitmq
      - redis
      - migration
    ports:
      - "8080:8080"

  worker:
    build: .
    env_file:
      - .env
    environment:
      - INSTANCE_TYPE=worker
    depends_on:
      - db
      - rabbitmq

  scheduler:
    build: .
    env_file:
      - .env
    environment:
      - INSTANCE_TYPE=beat
    depends_on:
      - db
      - rabbitmq

  migration:
    build: .
    env_file:
      - .env
    environment:
      - INSTANCE_TYPE=job
    depends_on:
      - db

volumes:
  postgres_data:
