services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./poms:/var/app/poms
    depends_on:
      - db
      - rabbitmq
      - redis
    restart: always
    ports:
      - "8000:8080"

  worker:
    build: .
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=poms_app.settings # remove after change manage.py location
      - INSTANCE_TYPE=worker
    depends_on:
      - db
      - rabbitmq
      - redis

  scheduler:
    build: .
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=poms_app.settings # remove after change manage.py location
      - INSTANCE_TYPE=beat
    depends_on:
      - db
      - rabbitmq
      - redis

  migration:
    build: .
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=poms_app.settings # remove after change manage.py location
      - INSTANCE_TYPE=job    
    depends_on:
      - db
      - redis
    
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finmars_dev
      POSTGRESQL_MAX_OPEN_CONNS: 500
    stdin_open: true
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    stdin_open: true
    tty: true

  redis:
    image: redis
    ports:
      - "6379:6379"
    stdin_open: true
    tty: true

volumes:
  postgres_data:
