services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./poms:/var/app/poms
    restart: always
    ports:
      - "8080:8080"

  worker:
    build: .
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=poms_app.settings
      - INSTANCE_TYPE=worker

  scheduler:
    build: .
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=poms_app.settings
      - INSTANCE_TYPE=beat

  migration:
    build: .
    env_file:
      - .env
    environment:
      - INSTANCE_TYPE=job

volumes:
  postgres_data:
