version: '2'
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finmars_dev
      POSTGRESQL_MAX_OPEN_CONNS: 500
    stdin_open: true
    tty: true
    ports:
      - "5434:5432"
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    stdin_open: true
    tty: true
  redis:
    image: redis
    ports:
      - "6379:6379"
    stdin_open: true
    tty: true