services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./poms:/var/app/poms
    restart: always
    depends_on:
      - db
      - rabbitmq
      - redis
      - backend_migration
    ports:
      - "8080:8080"

  worker:
    build: .
    env_file:
      - .env
    environment:
      - INSTANCE_TYPE=worker
    depends_on:
      - db
      - rabbitmq

  scheduler:
    build: .
    env_file:
      - .env
    environment:
      - INSTANCE_TYPE=beat
    depends_on:
      - db
      - rabbitmq

  backend_migration:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    command: python manage.py migrate_all_schemes

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finmars_dev
      POSTGRESQL_MAX_OPEN_CONNS: 500
    stdin_open: true
    tty: true
    ports:
      - "5434:5432"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    stdin_open: true
    tty: true

  redis:
    image: redis
    ports:
      - "6379:6379"
    stdin_open: true
    tty: true
