[project]
name = "finmars-backend"
version = "1.1.0"

[tool.isort]
profile="black"
py_version=310
known_django=[
    "django",
    "django_filters",
    "django_redis",
    "rest_framework",
    "drf_spectacular",
    "drf_yasg",
    "factory",
    "corsheaders"
]
sections=["FUTURE", "STDLIB", "DJANGO",  "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
skip=["__init__.py", ".gitignore", "templates"]
skip_glob=["venv/*"]

[tool.black]
line-length = 88
target-version = ["py310"]

[tool.ruff]
format = "grouped"
line-length = 88
ignore = ["E501", "F403", "F405"]
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
