# Generated by Django 4.2.16 on 2024-12-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0031_portfolio_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioreconcilegroup",
            name="params",
            field=models.JSONField(default=dict, verbose_name="calculation & reporting parameters"),
        ),
    ]
