# Generated by Django 4.2.16 on 2024-12-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0031_portfolio_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioreconcilegroup",
            name="precision",
            field=models.FloatField(default=1.0, verbose_name="compare precision"),
        ),
    ]
