# Generated by Django 4.2.16 on 2024-12-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0032_portfolioreconcilegroup_precision"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioreconcilegroup",
            name="report_params",
            field=models.JSONField(default=dict, verbose_name="report params"),
        ),
    ]
