GROUPS_PAYLOAD = {
    "account_mode": 1,
    "calculationGroup": "portfolio",
    "cost_method": 1,
    "filters": [],
    "portfolio_mode": 1,
    "pricing_policy": 5,
    "report_date": "2023-11-22",
    "strategy1_mode": 0,
    "strategy2_mode": 0,
    "strategy3_mode": 0,
    "table_font_size": "small",
    "frontend_request_options": {
        "groups_types": [{"value_type": 10}],
        "columns": [
            {
                "___column_id": "f448d162525bd5d940abda0167a17128",
                "columns": True,
                "key": "account.name",
                "name": "Account. Name",
                "options": {"sort": None, "sort_settings": {}},
                "style": {"width": "126px"},
                "value_type": 10,
            },
            {
                "___column_id": "8ebccdc298095b2f13ed7a0afe72cee9",
                "columns": True,
                "key": "account.notes",
                "name": "Account. Notes",
                "options": {"sort": None, "sort_settings": {}},
                "style": {"width": "138px"},
                "value_type": 10,
            },
            {
                "___column_id": "17cbdf8571c0a87d5d735dde3f74e3de",
                "columns": True,
                "key": "account.public_name",
                "name": "Account. Public name",
                "options": {"sort": None, "sort_settings": {}},
                "style": {"width": "153px"},
                "value_type": 10,
            },
            {
                "___column_id": "7602039b94de4191133dded740b3a00e",
                "columns": True,
                "key": "account.short_name",
                "name": "Account. Short name",
                "options": {"sort": None, "sort_settings": {}},
                "style": {"width": "173px"},
                "value_type": 10,
            },
            {
                "___column_id": "f06dc29edaf03b159a783c9d03541e8c",
                "columns": True,
                "key": "account.user_code",
                "name": "Account. User code",
                "options": {"sort": None, "sort_settings": {}},
                "style": {"width": "151px"},
                "value_type": 10,
            },
        ],
        "filter_settings": [],
    },
    "report_instance_id": 595,
}


ITEMS_PAYLOAD = {
    "account_mode": 1,
    "calculationGroup": "portfolio",
    "cost_method": 1,
    "filters": [],
    "portfolio_mode": 1,
    "pricing_policy": 5,
    "report_date": "2023-11-22",
    "strategy1_mode": 0,
    "strategy2_mode": 0,
    "strategy3_mode": 0,
    "table_font_size": "small",
    "page": 1,
    "page_size": 40,
    "frontend_request_options": {
        "groups_types": [],
        "page": 1,
        "groups_values": [],
        "groups_order": "asc",
        "page_size": 40,
        "filter_settings": [],
        "columns": [
            {
                "___column_id": "f448d162525bd5d940abda0167a17128",
                "columns": True,
                "key": "account.name",
                "name": "Account. Name",
                "options": {"sort": None, "sort_settings": {}},
                "style": {"width": "126px"},
                "value_type": 10,
            },
            {
                "___column_id": "8ebccdc298095b2f13ed7a0afe72cee9",
                "columns": True,
                "key": "account.notes",
                "name": "Account. Notes",
                "options": {"sort": None, "sort_settings": {}},
                "style": {"width": "138px"},
                "value_type": 10,
            },
            {
                "___column_id": "17cbdf8571c0a87d5d735dde3f74e3de",
                "columns": True,
                "key": "account.public_name",
                "name": "Account. Public name",
                "options": {"sort": None, "sort_settings": {}},
                "style": {"width": "153px"},
                "value_type": 10,
            },
            {
                "___column_id": "7602039b94de4191133dded740b3a00e",
                "columns": True,
                "key": "account.short_name",
                "name": "Account. Short name",
                "options": {"sort": None, "sort_settings": {}},
                "style": {"width": "173px"},
                "value_type": 10,
            },
            {
                "___column_id": "f06dc29edaf03b159a783c9d03541e8c",
                "columns": True,
                "key": "account.user_code",
                "name": "Account. User code",
                "options": {"sort": None, "sort_settings": {}},
                "style": {"width": "151px"},
                "value_type": 10,
            },
        ],
    },
}
