# Generated by Django 4.2.3 on 2024-07-11 18:38

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0012_accesspolicy_created_accesspolicy_modified_and_more"),
        ("users", "0013_remove_ecosystemdefault_currency_pricing_scheme_and_more"),
        ("explorer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupShare",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.group"
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iam.accesspolicy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberShare",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.member"
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iam.accesspolicy",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="finmarsfile",
            name="path",
            field=models.CharField(
                db_index=True,
                help_text="Path to the file in the storage system",
                max_length=2048,
            ),
        ),
        migrations.CreateModel(
            name="ShareAccessRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        db_index=True,
                        help_text="Path to the file/directory in the storage system",
                        max_length=2048,
                    ),
                ),
                (
                    "public_link_token",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("public_link_expires", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.member"
                    ),
                ),
                (
                    "public_link_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iam.accesspolicy",
                    ),
                ),
                (
                    "shared_with_groups",
                    models.ManyToManyField(
                        related_name="shared_files",
                        through="explorer.GroupShare",
                        to="iam.group",
                    ),
                ),
                (
                    "shared_with_users",
                    models.ManyToManyField(
                        related_name="shared_files",
                        through="explorer.MemberShare",
                        to="users.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="membershare",
            name="share_access_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="explorer.shareaccessrecord",
            ),
        ),
        migrations.AddField(
            model_name="groupshare",
            name="share_access_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="explorer.shareaccessrecord",
            ),
        ),
        migrations.CreateModel(
            name="FinmarsDirectory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Directory name (last part of the path)",
                        max_length=255,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        db_index=True,
                        help_text="Path to the directory in the storage system",
                        max_length=2048,
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("mptt_level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="explorer.finmarsdirectory",
                    ),
                ),
            ],
            options={
                "ordering": ["path", "name"],
            },
        ),
        migrations.AddField(
            model_name="finmarsfile",
            name="directory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="explorer.finmarsdirectory",
            ),
        ),
        migrations.AddConstraint(
            model_name="finmarsdirectory",
            constraint=models.UniqueConstraint(
                fields=("path", "name"), name="unique_directory_path"
            ),
        ),
    ]
